export const ReducerConstant = {
  // Reset Constant
  RESET_APP: 'RESET_APP',

  // App State Constant
  APP_AUTH_STATE: 'APP_AUTH_STATE',

  // User Data Constant
  HOME_START: 'HOME_START',
  HOME_SUCCESS: 'HOME_SUCCESS',
  HOME_ERROR: 'HOME_ERROR',
  HOME_WORLD_COVID_SUCCESS: 'HOME_WORLD_COVID_SUCCESS',
  HOME_COUNTRY_COVID_START: 'HOME_COUNTRY_COVID_START',
  HOME_COUNTRY_COVID_SUCCESS: 'HOME_COUNTRY_COVID_SUCCESS',
  HOME_COUNTRY_COVID_FAIL: 'HOME_COUNTRY_COVID_FAIL',

  // Error Constant
  ERROR_DIALOG: 'ERROR_DIALOG',
  ERROR_DIALOG_CLOSE: 'ERROR_DIALOG_CLOSE',
};